### ISSUE TITLE
Improvement: display long string dataset properly

### ISSUE THREAD

**Issue by kyang2014** [HDFGroup/hdf-compass#94] opened 2015-10-12 21:39 UTC
1. File: ftp://ftp.hdfgroup.uiuc.edu/pub/outgoing/HDFCompass/kent-files/hdf5-handler-fake/grid_1_2d.h5

2. Testing version: Windows version of the release candidate from S3

3. Issues
Compass display a long string dataset all in one line. It is hard to read. Should follow the way HDFView is using.

Read the string dataset  StructMetadata.0 under the group /HDFEOS INFORMATION and then check the same dataset with HDFView. You can see the differences.

**Comment by jreadey** [comment] 2015-10-13 02:09
Duplicate of #69.

**Closed by jreadey** 2015-10-13 02:09 UTC
Labels: duplicate
