### ISSUE TITLE
What does 'Open Resource' do?

### ISSUE THREAD

**Issue by gheber** [HDFGroup/hdf-compass#22] opened 2015-04-17 07:28 UTC
If I try to open http://tall.data.hdfgroup.org:7253/ , I get a pop-up "The following URL could not be opened:" ...

**Comment by jreadey** [comment] 2015-06-03 00:05
There's no plugin (yet!) for HDFServer.  
The OpenDAP plugin is working (at least on the Windows build).  Here's a sample resource to try out:
http://nsidc.org/opendap/MOSA/MYD10CM.005/2003.02.01/MYD10CM.A2003032.005.2008056200320.hdf

**Comment by gheber** [comment] 2015-06-03 11:25
Where do I get the plugin?

**Comment by jreadey** [comment] 2015-06-03 15:32
It's a builtin plugin (if that makes sense).  Doing "open resource" with the link above doesn't work for you?

There was an installer issue with PyDap on Mac, but I tried it out on the Windows release.

**Comment by gheber** [comment] 2015-06-03 15:33
No

**Comment by jreadey** [comment] 2015-06-03 15:38
Looks like a regression in the setup.  It's not working for me either (though it's fine if I run Compass from the project directory).

**Comment by jreadey** [comment] 2015-10-28 03:40
Closing since "how to" questions should be addressed by the user guide (#76).

**Closed by jreadey** 2015-10-28 03:40 UTC
Labels: question
