### ISSUE TITLE
Nice tool

### ISSUE THREAD

**Issue by ganymede42** [HDFGroup/hdf-compass#45] opened 2015-06-16 13:03 UTC
Hi all

Looks very promising. It's a pity, that h5pyViewer project that I started one year earlier did not get contributions and support as this one...
https://github.com/ganymede42/h5pyViewer
Perhaps you can use some ideas of that code base.
Regards

**Comment by Juanlu001** [comment] 2015-06-23 16:13
@ganymede42 What is the license of h5pyViewer? The choice is important for reusing the code, and apparently there is none. Nice project by the way!

**Comment by ganymede42** [comment] 2015-06-24 07:03
Hello Juan Luis

I did not yet care a lot about the licence type of that project. Anyway:
The code I wrote is free to reuse. I just wants, that my name and company
stays in the source and that the code keeps free.

So if I am correct a GPL would fullfill these requirements. So as you now
much more about licencing: what do you recommand to me to write about
licencing?

I am using: h5py, numpy wxPython and some other python libraries.

Do you need more informations about that.

**Comment by jreadey** [comment] 2015-06-24 07:09
Unless you want to prevent people from using your software in any non-GPL application, you probably want a BSD-style license.  See: https://en.wikipedia.org/wiki/BSD_licenses.

**Comment by Juanlu001** [comment] 2015-06-24 07:17
Yeah, most Python libraries have BSD-like licenses. They are more permissive and allow for commercial, closed uses.

**Comment by Juanlu001** [comment] 2015-06-24 07:19
http://choosealicense.com/licenses/

**Comment by ganymede42** [comment] 2015-06-24 07:31
Thanks you for your link. I is just difficult to now, which licence type is correct to write, so that I do not violate a licence of a library that I use. So Yes, BSD-style license sounds good. I will add this to the github repo soon. Is that ok for you?

**Comment by Juanlu001** [comment] 2015-06-24 07:40
Yes totally! It will surely make easier and clearer for others to reuse the code without concerns :)

**Comment by ganymede42** [comment] 2015-06-25 10:09
Now h5pyViewer has a BSD 2-clause licence. So feel free. Of course I would like that my project and my name is referred in the code of it is reused ;-).

**Comment by Juanlu001** [comment] 2015-06-25 10:17
On Jun 25, 2015 12:09 PM, "Thierry Zamofing" <notifications@github.com>
wrote:
>
> Of course I would like that my project and my name is referred in the
code of it is reused ;-).
>

Those are exactly the terms of the license ;)

**Comment by jreadey** [comment] 2015-10-28 03:36
Closing since this is not a bug report!

**Closed by jreadey** 2015-10-28 03:36 UTC
